### ISSUE TITLE
ConnectionManager.teardownConnection(device) is making my app crash.

### ISSUE THREAD

**Issue by Soumennn** [PunchThrough/ble-starter-android#18]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.halosleep.bassinest, PID: 20612
    java.lang.IllegalArgumentException: Navigation action/destination com.halosleep.bassinest:id/action_connectionLoadingFragment_to_errorFragment cannot be found from the current destination Destination(com.halosleep.bassinest:id/bleScanFragment) label=fragment_ble_scan class=com.halosleep.bassinest.ui.activity.wifi.wifiFragments.BleScanFragment
        at androidx.navigation.NavController.navigate(NavController.kt:1540)
        at androidx.navigation.NavController.navigate(NavController.kt:1472)
        at androidx.navigation.NavController.navigate(NavController.kt:1930)
        at com.halosleep.bassinest.ui.activity.wifi.wifiFragments.BleScanFragment$moveToErrorPage$1.invokeSuspend(BleScanFragment.kt:464)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7884)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@47f45d4, Dispatchers.Main]

**Comment by cheeyi** [comment]
It looks like the crash may have occurred in your app logic (Compose Navigation?) rather than in this library's code.

**Comment by Soumennn** [comment]
Yes, you are correct
