### ISSUE TITLE
The app is not working on tablet

### ISSUE THREAD

**Issue by harsimranSandhu** [PunchThrough/ble-starter-android#5]
Here is the error i am getting in my logcat while running on tablet.

2021-05-11 13:20:22.073 24893-24893/? I/arterappandroi: Late-enabling -Xcheck:jni
2021-05-11 13:20:22.104 24893-24893/? E/arterappandroi: Unknown bits set in runtime_flags: 0x8000
2021-05-11 13:20:22.140 24893-24911/? D/Typeface: Invalid or same font: 
2021-05-11 13:20:22.451 24893-24893/com.punchthrough.blestarterappandroid W/arterappandroi: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2021-05-11 13:20:22.453 24893-24893/com.punchthrough.blestarterappandroid W/arterappandroi: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2021-05-11 13:20:22.521 24893-24893/com.punchthrough.blestarterappandroid D/ConnectionManager: Added listener com.punchthrough.blestarterappandroid.ble.ConnectionEventListener@b4f48c4, 1 listeners total
2021-05-11 13:20:22.528 24893-24893/com.punchthrough.blestarterappandroid I/SurfaceFactory: [static] sSurfaceFactory = com.mediatek.view.impl.SurfaceFactoryImpl@7368a73
2021-05-11 13:20:22.540 24893-24893/com.punchthrough.blestarterappandroid D/ViewRootImpl[MainActivity]: hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
2021-05-11 13:20:22.546 24893-24893/com.punchthrough.blestarterappandroid V/PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@8655acf, this = DecorView@fecec5c[MainActivity]
2021-05-11 13:20:22.602 24893-24893/com.punchthrough.blestarterappandroid E/GraphicExt: Can't load libboost_ext_fwk
2021-05-11 13:20:22.602 24893-24893/com.punchthrough.blestarterappandroid E/GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
2021-05-11 13:20:22.603 24893-24923/com.punchthrough.blestarterappandroid I/GPUD: @gpudInitialize: successfully initialized with GL, dbg=0 mmdump_dbg=0 mmpath_dbg=0
2021-05-11 13:20:22.624 24893-24923/com.punchthrough.blestarterappandroid D/Surface: Surface::connect(this=0x756453f000,api=1)
2021-05-11 13:20:22.626 24893-24923/com.punchthrough.blestarterappandroid D/Surface: Surface::setBufferCount(this=0x756453f000,bufferCount=3)
2021-05-11 13:20:22.626 24893-24923/com.punchthrough.blestarterappandroid D/Surface: Surface::allocateBuffers(this=0x756453f000)
2021-05-11 13:20:22.636 24893-24923/com.punchthrough.blestarterappandroid W/Gralloc3: mapper 3.x is not supported
2021-05-11 13:20:22.638 24893-24923/com.punchthrough.blestarterappandroid E/ion: ioctl c0044901 failed with code -1: Invalid argument
2021-05-11 13:23:56.909 24893-24893/com.punchthrough.blestarterappandroid D/ScrollableViewRECUtil: user cancel scrollshot 
    java.lang.Throwable
        at android.util.screenscrollshot.ScrollableViewRECUtil.cancel(ScrollableViewRECUtil.java:287)
        at android.app.Activity.onScrollScreenshotCancel(Activity.java:972)
        at android.app.Activity.onStop(Activity.java:2505)
        at androidx.fragment.app.FragmentActivity.onStop(FragmentActivity.java:559)
        at androidx.appcompat.app.AppCompatActivity.onStop(AppCompatActivity.java:216)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1473)
        at android.app.Activity.performStop(Activity.java:8089)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4648)
        at android.app.ActivityThread.handleSleeping(ActivityThread.java:4785)
        at android.app.ActivityThread.access$2600(ActivityThread.java:227)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1986)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7405)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
2021-05-11 13:23:56.918 24893-24923/com.punchthrough.blestarterappandroid I/GED: ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
2021-05-11 13:24:01.735 24893-24923/com.punchthrough.blestarterappandroid D/Surface: Surface::disconnect(this=0x756453f000,api=1)
2021-05-11 13:24:01.755 24893-24893/com.punchthrough.blestarterappandroid V/PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@8655acf, this = DecorView@fecec5c[MainActivity]

**Comment by cheeyi** [comment]
Hi @harsimranSandhu the app is currently not optimized for tablet in any way, it's only meant as a sample app to demonstrate our Bluetooth capabilities on phone-sized screens. That said, I'll keep this ticket open for when we have time to make further updates. Thanks.

**Comment by bhupalreddykokkanti** [comment]
Hi @cheeyi is the compatibility with Tablet is fixed. Any update on it. Actually we are waiting for it

**Comment by cheeyi** [comment]
@bhupalreddykokkanti @harsimranSandhu it looks like the original issue that was posted is not relevant to this project as the crash was caused by `android.util.screenscrollshot.ScrollableViewRECUtil.cancel(ScrollableViewRECUtil.java:287)`.

If you're still running into Bluetooth-specific errors please feel free to fix it and open a pull request.
